FROM php:7.4-fpm-alpine
RUN apk add $PHPIZE_DEPS zlib-dev libpng-dev mysql-dev && \
	pecl install xdebug

RUN docker-php-ext-install gd pdo pdo_mysql

CMD '/bin/chmod' '-R' '777' '/code/storage'
CMD 'php-fpm'
