version: "3"
services:
  php:
    build: ./docker/php
    volumes:
      - ./:/code
    network_mode: host
  web:
    image: nginx:mainline-alpine
    volumes:
      - ./:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    network_mode: host
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: koer
      MYSQL_USER: koer
      MYSQL_PASSWORD: koer
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    network_mode: host
volumes:
  db-data:
